export const LASTEST_BLOCKS_REQUEST: "LASTEST_BLOCKS_REQUEST" = "LASTEST_BLOCKS_REQUEST"
export const LASTEST_BLOCKS_SUCCESS: "LASTEST_BLOCKS_SUCCESS" = "LASTEST_BLOCKS_SUCCESS"
export const LASTEST_BLOCKS_FAILURE: "LASTEST_BLOCKS_FAILURE" = "LASTEST_BLOCKS_FAILURE"
